Insert into D_STD_FORMSTATUS_H (FORMSTATUS_ID,FORMSTATUS_NAME,FORMSTATUS_CODE) values ('EMPTY','1. empty','FORMSTATUS_EMPTY');
Insert into D_STD_FORMSTATUS_H (FORMSTATUS_ID,FORMSTATUS_NAME,FORMSTATUS_CODE) values ('PARTIALLY_FILLED','2. partially completed','FORMSTATUS_PARTIALLY_FILLED');
Insert into D_STD_FORMSTATUS_H (FORMSTATUS_ID,FORMSTATUS_NAME,FORMSTATUS_CODE) values ('COMPLETELY_FILLED','3. fully completed','FORMSTATUS_COMPLETELY_FILLED');

Insert into D_STD_QUERYSTATUS_H (QUERYSTATUS_ID,QUERYSTATUS_NAME,QUERYSTATUS_CODE) values ('WITHOUT_QUERIES','0. Forms without queries','QUERYSTATUS_WITHOUT_QUERIES');
Insert into D_STD_QUERYSTATUS_H (QUERYSTATUS_ID,QUERYSTATUS_NAME,QUERYSTATUS_CODE) values ('WITH_OPEN_QUERIES','1. Forms with open queries','QUERYSTATUS_WITH_OPEN_QUERIES');
Insert into D_STD_QUERYSTATUS_H (QUERYSTATUS_ID,QUERYSTATUS_NAME,QUERYSTATUS_CODE) values ('WITH_ANSWERED_QUERIES','2. Forms with answered queries','QUERYSTATUS_WITH_ANSWERED_QUERIES');
Insert into D_STD_QUERYSTATUS_H (QUERYSTATUS_ID,QUERYSTATUS_NAME,QUERYSTATUS_CODE) values ('ALL_QUERIES_CLOSED','3. Forms with only closed queries','QUERYSTATUS_ALL_QUERIES_CLOSED');

Insert into D_STD_STUDYEVENT_STATUS_H (STUDYEVENT_STATUS_ID,STUDYEVENT_STATUS_NAME,STUDYEVENT_STATUS_CODE) values ('OPEN','1. not started','STUDYEVENT_STATUS_OPEN');
Insert into D_STD_STUDYEVENT_STATUS_H (STUDYEVENT_STATUS_ID,STUDYEVENT_STATUS_NAME,STUDYEVENT_STATUS_CODE) values ('ONGOING','2. in progress','STUDYEVENT_STATUS_ONGOING');
Insert into D_STD_STUDYEVENT_STATUS_H (STUDYEVENT_STATUS_ID,STUDYEVENT_STATUS_NAME,STUDYEVENT_STATUS_CODE) values ('FINISHED','3. finalized','STUDYEVENT_STATUS_FINISHED');

INSERT INTO D_STD_PATIENTSTATES_H (PATIENTSTATE_ID,PATIENTSTATE_NAME,PATIENTSTATE_CODE,PATIENTSTATE_ORDER,PATIENTSTATE_ONLYNAME) values ('SCR','1. Screening','SCR',1,'Screening');
INSERT INTO D_STD_PATIENTSTATES_H (PATIENTSTATE_ID,PATIENTSTATE_NAME,PATIENTSTATE_CODE,PATIENTSTATE_ORDER,PATIENTSTATE_ONLYNAME) values ('SFL','2. Screening failure','SFL',2,'Screening failure');
INSERT INTO D_STD_PATIENTSTATES_H (PATIENTSTATE_ID,PATIENTSTATE_NAME,PATIENTSTATE_CODE,PATIENTSTATE_ORDER,PATIENTSTATE_ONLYNAME) values ('ACT','3. Active','ACT',3,'Active');
INSERT INTO D_STD_PATIENTSTATES_H (PATIENTSTATE_ID,PATIENTSTATE_NAME,PATIENTSTATE_CODE,PATIENTSTATE_ORDER,PATIENTSTATE_ONLYNAME) values ('IRG','4. Dropout','IRG',4,'Dropout');
INSERT INTO D_STD_PATIENTSTATES_H (PATIENTSTATE_ID,PATIENTSTATE_NAME,PATIENTSTATE_CODE,PATIENTSTATE_ORDER,PATIENTSTATE_ONLYNAME) values ('REG','5. Completed study','REG',5,'Completed study');
INSERT INTO D_STD_PATIENTSTATES_H (PATIENTSTATE_ID,PATIENTSTATE_NAME,PATIENTSTATE_CODE,PATIENTSTATE_ORDER,PATIENTSTATE_ONLYNAME) values ('GAP','6. Gap','REG',6,'Gap');
